spring.application.name=server

#spring.datasource.url=jdbc:postgresql://localhost:5432/elec_maintenance
#spring.datasource.username=elec_root
#spring.datasource.password=1q2w3e4r

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true